export type CountryOption = { code: string; name: string };

export const ISO_COUNTRIES: CountryOption[] = [
	{ code: "AF", name: "Afghanistan" },
	{ code: "AL", name: "Albania" },
	{ code: "DZ", name: "Algeria" },
	{ code: "AS", name: "American Samoa" },
	{ code: "AD", name: "Andorra" },
	{ code: "AO", name: "Angola" },
	{ code: "AI", name: "Anguilla" },
	{ code: "AQ", name: "Antarctica" },
	{ code: "AG", name: "Antigua and Barbuda" },
	{ code: "AR", name: "Argentina" },
	{ code: "AM", name: "Armenia" },
	{ code: "AW", name: "Aruba" },
	{ code: "AU", name: "Australia" },
	{ code: "AT", name: "Austria" },
	{ code: "AZ", name: "Azerbaijan" },
	{ code: "BS", name: "Bahamas" },
	{ code: "BH", name: "Bahrain" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "BB", name: "Barbados" },
	{ code: "BY", name: "Belarus" },
	{ code: "BE", name: "Belgium" },
	{ code: "BZ", name: "Belize" },
	{ code: "BJ", name: "Benin" },
	{ code: "BM", name: "Bermuda" },
	{ code: "BT", name: "Bhutan" },
	{ code: "BO", name: "Bolivia" },
	{ code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "BW", name: "Botswana" },
	{ code: "BV", name: "Bouvet Island" },
	{ code: "BR", name: "Brazil" },
	{ code: "IO", name: "British Indian Ocean Territory" },
	{ code: "BN", name: "Brunei Darussalam" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "BI", name: "Burundi" },
	{ code: "CV", name: "Cabo Verde" },
	{ code: "KH", name: "Cambodia" },
	{ code: "CM", name: "Cameroon" },
	{ code: "CA", name: "Canada" },
	{ code: "KY", name: "Cayman Islands" },
	{ code: "CF", name: "Central African Republic" },
	{ code: "TD", name: "Chad" },
	{ code: "CL", name: "Chile" },
	{ code: "CN", name: "China" },
	{ code: "CX", name: "Christmas Island" },
	{ code: "CC", name: "Cocos (Keeling) Islands" },
	{ code: "CO", name: "Colombia" },
	{ code: "KM", name: "Comoros" },
	{ code: "CG", name: "Congo" },
	{ code: "CD", name: "Congo, Democratic Republic of the" },
	{ code: "CK", name: "Cook Islands" },
	{ code: "CR", name: "Costa Rica" },
	{ code: "HR", name: "Croatia" },
	{ code: "CU", name: "Cuba" },
	{ code: "CW", name: "Curaçao" },
	{ code: "CY", name: "Cyprus" },
	{ code: "CZ", name: "Czechia" },
	{ code: "CI", name: "Côte d'Ivoire" },
	{ code: "DK", name: "Denmark" },
	{ code: "DJ", name: "Djibouti" },
	{ code: "DM", name: "Dominica" },
	{ code: "DO", name: "Dominican Republic" },
	{ code: "EC", name: "Ecuador" },
	{ code: "EG", name: "Egypt" },
	{ code: "SV", name: "El Salvador" },
	{ code: "GQ", name: "Equatorial Guinea" },
	{ code: "ER", name: "Eritrea" },
	{ code: "EE", name: "Estonia" },
	{ code: "SZ", name: "Eswatini" },
	{ code: "ET", name: "Ethiopia" },
	{ code: "FK", name: "Falkland Islands" },
	{ code: "FO", name: "Faroe Islands" },
	{ code: "FJ", name: "Fiji" },
	{ code: "FI", name: "Finland" },
	{ code: "FR", name: "France" },
	{ code: "GF", name: "French Guiana" },
	{ code: "PF", name: "French Polynesia" },
	{ code: "TF", name: "French Southern Territories" },
	{ code: "GA", name: "Gabon" },
	{ code: "GM", name: "Gambia" },
	{ code: "GE", name: "Georgia" },
	{ code: "DE", name: "Germany" },
	{ code: "GH", name: "Ghana" },
	{ code: "GI", name: "Gibraltar" },
	{ code: "GR", name: "Greece" },
	{ code: "GL", name: "Greenland" },
	{ code: "GD", name: "Grenada" },
	{ code: "GP", name: "Guadeloupe" },
	{ code: "GU", name: "Guam" },
	{ code: "GT", name: "Guatemala" },
	{ code: "GG", name: "Guernsey" },
	{ code: "GN", name: "Guinea" },
	{ code: "GW", name: "Guinea-Bissau" },
	{ code: "GY", name: "Guyana" },
	{ code: "HT", name: "Haiti" },
	{ code: "HM", name: "Heard Island and McDonald Islands" },
	{ code: "VA", name: "Holy See" },
	{ code: "HN", name: "Honduras" },
	{ code: "HK", name: "Hong Kong" },
	{ code: "HU", name: "Hungary" },
	{ code: "IS", name: "Iceland" },
	{ code: "IN", name: "India" },
	{ code: "ID", name: "Indonesia" },
	{ code: "IR", name: "Iran" },
	{ code: "IQ", name: "Iraq" },
	{ code: "IE", name: "Ireland" },
	{ code: "IM", name: "Isle of Man" },
	{ code: "IL", name: "Israel" },
	{ code: "IT", name: "Italy" },
	{ code: "JM", name: "Jamaica" },
	{ code: "JP", name: "Japan" },
	{ code: "JE", name: "Jersey" },
	{ code: "JO", name: "Jordan" },
	{ code: "KZ", name: "Kazakhstan" },
	{ code: "KE", name: "Kenya" },
	{ code: "KI", name: "Kiribati" },
	{ code: "KP", name: "Korea, Democratic People's Republic of" },
	{ code: "KR", name: "Korea, Republic of" },
	{ code: "KW", name: "Kuwait" },
	{ code: "KG", name: "Kyrgyzstan" },
	{ code: "LA", name: "Lao People's Democratic Republic" },
	{ code: "LV", name: "Latvia" },
	{ code: "LB", name: "Lebanon" },
	{ code: "LS", name: "Lesotho" },
	{ code: "LR", name: "Liberia" },
	{ code: "LY", name: "Libya" },
	{ code: "LI", name: "Liechtenstein" },
	{ code: "LT", name: "Lithuania" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "MO", name: "Macao" },
	{ code: "MG", name: "Madagascar" },
	{ code: "MW", name: "Malawi" },
	{ code: "MY", name: "Malaysia" },
	{ code: "MV", name: "Maldives" },
	{ code: "ML", name: "Mali" },
	{ code: "MT", name: "Malta" },
	{ code: "MH", name: "Marshall Islands" },
	{ code: "MQ", name: "Martinique" },
	{ code: "MR", name: "Mauritania" },
	{ code: "MU", name: "Mauritius" },
	{ code: "YT", name: "Mayotte" },
	{ code: "MX", name: "Mexico" },
	{ code: "FM", name: "Micronesia" },
	{ code: "MD", name: "Moldova" },
	{ code: "MC", name: "Monaco" },
	{ code: "MN", name: "Mongolia" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MS", name: "Montserrat" },
	{ code: "MA", name: "Morocco" },
	{ code: "MZ", name: "Mozambique" },
	{ code: "MM", name: "Myanmar" },
	{ code: "NA", name: "Namibia" },
	{ code: "NR", name: "Nauru" },
	{ code: "NP", name: "Nepal" },
	{ code: "NL", name: "Netherlands" },
	{ code: "NC", name: "New Caledonia" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "NI", name: "Nicaragua" },
	{ code: "NE", name: "Niger" },
	{ code: "NG", name: "Nigeria" },
	{ code: "NU", name: "Niue" },
	{ code: "NF", name: "Norfolk Island" },
	{ code: "MK", name: "North Macedonia" },
	{ code: "MP", name: "Northern Mariana Islands" },
	{ code: "NO", name: "Norway" },
	{ code: "OM", name: "Oman" },
	{ code: "PK", name: "Pakistan" },
	{ code: "PW", name: "Palau" },
	{ code: "PS", name: "Palestine, State of" },
	{ code: "PA", name: "Panama" },
	{ code: "PG", name: "Papua New Guinea" },
	{ code: "PY", name: "Paraguay" },
	{ code: "PE", name: "Peru" },
	{ code: "PH", name: "Philippines" },
	{ code: "PN", name: "Pitcairn" },
	{ code: "PL", name: "Poland" },
	{ code: "PT", name: "Portugal" },
	{ code: "PR", name: "Puerto Rico" },
	{ code: "QA", name: "Qatar" },
	{ code: "RO", name: "Romania" },
	{ code: "RU", name: "Russian Federation" },
	{ code: "RW", name: "Rwanda" },
	{ code: "RE", name: "Réunion" },
	{ code: "BL", name: "Saint Barthélemy" },
	{ code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
	{ code: "KN", name: "Saint Kitts and Nevis" },
	{ code: "LC", name: "Saint Lucia" },
	{ code: "MF", name: "Saint Martin (French part)" },
	{ code: "PM", name: "Saint Pierre and Miquelon" },
	{ code: "VC", name: "Saint Vincent and the Grenadines" },
	{ code: "WS", name: "Samoa" },
	{ code: "SM", name: "San Marino" },
	{ code: "ST", name: "Sao Tome and Principe" },
	{ code: "SA", name: "Saudi Arabia" },
	{ code: "SN", name: "Senegal" },
	{ code: "RS", name: "Serbia" },
	{ code: "SC", name: "Seychelles" },
	{ code: "SL", name: "Sierra Leone" },
	{ code: "SG", name: "Singapore" },
	{ code: "SX", name: "Sint Maarten (Dutch part)" },
	{ code: "SK", name: "Slovakia" },
	{ code: "SI", name: "Slovenia" },
	{ code: "SB", name: "Solomon Islands" },
	{ code: "SO", name: "Somalia" },
	{ code: "ZA", name: "South Africa" },
	{ code: "GS", name: "South Georgia and the South Sandwich Islands" },
	{ code: "SS", name: "South Sudan" },
	{ code: "ES", name: "Spain" },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "SD", name: "Sudan" },
	{ code: "SR", name: "Suriname" },
	{ code: "SJ", name: "Svalbard and Jan Mayen" },
	{ code: "SE", name: "Sweden" },
	{ code: "CH", name: "Switzerland" },
	{ code: "SY", name: "Syrian Arab Republic" },
	{ code: "TW", name: "Taiwan" },
	{ code: "TJ", name: "Tajikistan" },
	{ code: "TZ", name: "Tanzania" },
	{ code: "TH", name: "Thailand" },
	{ code: "TL", name: "Timor-Leste" },
	{ code: "TG", name: "Togo" },
	{ code: "TK", name: "Tokelau" },
	{ code: "TO", name: "Tonga" },
	{ code: "TT", name: "Trinidad and Tobago" },
	{ code: "TN", name: "Tunisia" },
	{ code: "TM", name: "Turkmenistan" },
	{ code: "TC", name: "Turks and Caicos Islands" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "TR", name: "Türkiye" },
	{ code: "UG", name: "Uganda" },
	{ code: "UA", name: "Ukraine" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "US", name: "United States" },
	{ code: "UM", name: "United States Minor Outlying Islands" },
	{ code: "UY", name: "Uruguay" },
	{ code: "UZ", name: "Uzbekistan" },
	{ code: "VU", name: "Vanuatu" },
	{ code: "VE", name: "Venezuela" },
	{ code: "VN", name: "Viet Nam" },
	{ code: "VG", name: "Virgin Islands (British)" },
	{ code: "VI", name: "Virgin Islands (U.S.)" },
	{ code: "WF", name: "Wallis and Futuna" },
	{ code: "EH", name: "Western Sahara" },
	{ code: "YE", name: "Yemen" },
	{ code: "ZM", name: "Zambia" },
	{ code: "ZW", name: "Zimbabwe" },
	{ code: "AX", name: "Åland Islands" },
];

const ISO_CODES = new Set(ISO_COUNTRIES.map((c) => c.code));

function aliasKey(value: string): string {
	return value.trim().toUpperCase().replace(/,/g, " ").replace(/\s+/g, " ");
}

const COUNTRY_ALIASES: Record<string, string> = {
	"AFGHANISTAN": "AF",
	"ALBANIA": "AL",
	"ALGERIA": "DZ",
	"AMERICA": "US",
	"AMERICAN SAMOA": "AS",
	"ANDORRA": "AD",
	"ANGOLA": "AO",
	"ANGUILLA": "AI",
	"ANTARCTICA": "AQ",
	"ANTIGUA AND BARBUDA": "AG",
	"ARGENTINA": "AR",
	"ARMENIA": "AM",
	"ARUBA": "AW",
	"AUSTRALIA": "AU",
	"AUSTRIA": "AT",
	"AZERBAIJAN": "AZ",
	"BAHAMAS": "BS",
	"BAHRAIN": "BH",
	"BANGLADESH": "BD",
	"BARBADOS": "BB",
	"BELARUS": "BY",
	"BELGIUM": "BE",
	"BELIZE": "BZ",
	"BENIN": "BJ",
	"BERMUDA": "BM",
	"BHUTAN": "BT",
	"BOLIVIA": "BO",
	"BONAIRE SINT EUSTATIUS AND SABA": "BQ",
	"BOSNIA AND HERZEGOVINA": "BA",
	"BOTSWANA": "BW",
	"BOUVET ISLAND": "BV",
	"BRAZIL": "BR",
	"BRITAIN": "GB",
	"BRITISH INDIAN OCEAN TERRITORY": "IO",
	"BRUNEI": "BN",
	"BRUNEI DARUSSALAM": "BN",
	"BULGARIA": "BG",
	"BURKINA FASO": "BF",
	"BURUNDI": "BI",
	"CABO VERDE": "CV",
	"CAMBODIA": "KH",
	"CAMEROON": "CM",
	"CANADA": "CA",
	"CAYMAN ISLANDS": "KY",
	"CENTRAL AFRICAN REPUBLIC": "CF",
	"CHAD": "TD",
	"CHILE": "CL",
	"CHINA": "CN",
	"CHRISTMAS ISLAND": "CX",
	"COCOS (KEELING) ISLANDS": "CC",
	"COLOMBIA": "CO",
	"COMOROS": "KM",
	"CONGO": "CG",
	"CONGO DEMOCRATIC REPUBLIC OF THE": "CD",
	"COOK ISLANDS": "CK",
	"COSTA RICA": "CR",
	"CROATIA": "HR",
	"CUBA": "CU",
	"CURAÇAO": "CW",
	"CYPRUS": "CY",
	"CZECH REPUBLIC": "CZ",
	"CZECHIA": "CZ",
	"CÔTE D'IVOIRE": "CI",
	"DENMARK": "DK",
	"DJIBOUTI": "DJ",
	"DOMINICA": "DM",
	"DOMINICAN REPUBLIC": "DO",
	"ECUADOR": "EC",
	"EGYPT": "EG",
	"EL SALVADOR": "SV",
	"ENGLAND": "GB",
	"EQUATORIAL GUINEA": "GQ",
	"ERITREA": "ER",
	"ESTONIA": "EE",
	"ESWATINI": "SZ",
	"ETHIOPIA": "ET",
	"FALKLAND ISLANDS": "FK",
	"FAROE ISLANDS": "FO",
	"FIJI": "FJ",
	"FINLAND": "FI",
	"FRANCE": "FR",
	"FRENCH GUIANA": "GF",
	"FRENCH POLYNESIA": "PF",
	"FRENCH SOUTHERN TERRITORIES": "TF",
	"GABON": "GA",
	"GAMBIA": "GM",
	"GEORGIA": "GE",
	"GERMANY": "DE",
	"GHANA": "GH",
	"GIBRALTAR": "GI",
	"GREAT BRITAIN": "GB",
	"GREECE": "GR",
	"GREENLAND": "GL",
	"GRENADA": "GD",
	"GUADELOUPE": "GP",
	"GUAM": "GU",
	"GUATEMALA": "GT",
	"GUERNSEY": "GG",
	"GUINEA": "GN",
	"GUINEA-BISSAU": "GW",
	"GUYANA": "GY",
	"HAITI": "HT",
	"HEARD ISLAND AND MCDONALD ISLANDS": "HM",
	"HOLLAND": "NL",
	"HOLY SEE": "VA",
	"HONDURAS": "HN",
	"HONG KONG": "HK",
	"HUNGARY": "HU",
	"ICELAND": "IS",
	"INDIA": "IN",
	"INDONESIA": "ID",
	"IRAN": "IR",
	"IRAQ": "IQ",
	"IRELAND": "IE",
	"ISLE OF MAN": "IM",
	"ISRAEL": "IL",
	"ITALY": "IT",
	"IVORY COAST": "CI",
	"JAMAICA": "JM",
	"JAPAN": "JP",
	"JERSEY": "JE",
	"JORDAN": "JO",
	"KAZAKHSTAN": "KZ",
	"KENYA": "KE",
	"KIRIBATI": "KI",
	"KOREA DEMOCRATIC PEOPLE'S REPUBLIC OF": "KP",
	"KOREA REPUBLIC OF": "KR",
	"KUWAIT": "KW",
	"KYRGYZSTAN": "KG",
	"LAO PEOPLE'S DEMOCRATIC REPUBLIC": "LA",
	"LAOS": "LA",
	"LATVIA": "LV",
	"LEBANON": "LB",
	"LESOTHO": "LS",
	"LIBERIA": "LR",
	"LIBYA": "LY",
	"LIECHTENSTEIN": "LI",
	"LITHUANIA": "LT",
	"LUXEMBOURG": "LU",
	"MACAO": "MO",
	"MACEDONIA": "MK",
	"MADAGASCAR": "MG",
	"MALAWI": "MW",
	"MALAYSIA": "MY",
	"MALDIVES": "MV",
	"MALI": "ML",
	"MALTA": "MT",
	"MARSHALL ISLANDS": "MH",
	"MARTINIQUE": "MQ",
	"MAURITANIA": "MR",
	"MAURITIUS": "MU",
	"MAYOTTE": "YT",
	"MEXICO": "MX",
	"MICRONESIA": "FM",
	"MOLDOVA": "MD",
	"MONACO": "MC",
	"MONGOLIA": "MN",
	"MONTENEGRO": "ME",
	"MONTSERRAT": "MS",
	"MOROCCO": "MA",
	"MOZAMBIQUE": "MZ",
	"MYANMAR": "MM",
	"NAMIBIA": "NA",
	"NAURU": "NR",
	"NEPAL": "NP",
	"NETHERLANDS": "NL",
	"NEW CALEDONIA": "NC",
	"NEW ZEALAND": "NZ",
	"NICARAGUA": "NI",
	"NIGER": "NE",
	"NIGERIA": "NG",
	"NIUE": "NU",
	"NORFOLK ISLAND": "NF",
	"NORTH KOREA": "KP",
	"NORTH MACEDONIA": "MK",
	"NORTHERN MARIANA ISLANDS": "MP",
	"NORWAY": "NO",
	"OMAN": "OM",
	"PAKISTAN": "PK",
	"PALAU": "PW",
	"PALESTINE": "PS",
	"PALESTINE STATE OF": "PS",
	"PANAMA": "PA",
	"PAPUA NEW GUINEA": "PG",
	"PARAGUAY": "PY",
	"PERU": "PE",
	"PHILIPPINES": "PH",
	"PITCAIRN": "PN",
	"POLAND": "PL",
	"PORTUGAL": "PT",
	"PUERTO RICO": "PR",
	"QATAR": "QA",
	"REPUBLIC OF KOREA": "KR",
	"ROMANIA": "RO",
	"RUSSIA": "RU",
	"RUSSIAN FEDERATION": "RU",
	"RWANDA": "RW",
	"RÉUNION": "RE",
	"SAINT BARTHÉLEMY": "BL",
	"SAINT HELENA ASCENSION AND TRISTAN DA CUNHA": "SH",
	"SAINT KITTS AND NEVIS": "KN",
	"SAINT LUCIA": "LC",
	"SAINT MARTIN (FRENCH PART)": "MF",
	"SAINT PIERRE AND MIQUELON": "PM",
	"SAINT VINCENT AND THE GRENADINES": "VC",
	"SAMOA": "WS",
	"SAN MARINO": "SM",
	"SAO TOME AND PRINCIPE": "ST",
	"SAUDI ARABIA": "SA",
	"SCOTLAND": "GB",
	"SENEGAL": "SN",
	"SERBIA": "RS",
	"SEYCHELLES": "SC",
	"SIERRA LEONE": "SL",
	"SINGAPORE": "SG",
	"SINT MAARTEN (DUTCH PART)": "SX",
	"SLOVAKIA": "SK",
	"SLOVENIA": "SI",
	"SOLOMON ISLANDS": "SB",
	"SOMALIA": "SO",
	"SOUTH AFRICA": "ZA",
	"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS": "GS",
	"SOUTH KOREA": "KR",
	"SOUTH SUDAN": "SS",
	"SPAIN": "ES",
	"SRI LANKA": "LK",
	"SUDAN": "SD",
	"SURINAME": "SR",
	"SVALBARD AND JAN MAYEN": "SJ",
	"SWAZILAND": "SZ",
	"SWEDEN": "SE",
	"SWITZERLAND": "CH",
	"SYRIA": "SY",
	"SYRIAN ARAB REPUBLIC": "SY",
	"TAIWAN": "TW",
	"TAJIKISTAN": "TJ",
	"TANZANIA": "TZ",
	"THAILAND": "TH",
	"THE NETHERLANDS": "NL",
	"TIMOR-LESTE": "TL",
	"TOGO": "TG",
	"TOKELAU": "TK",
	"TONGA": "TO",
	"TRINIDAD AND TOBAGO": "TT",
	"TUNISIA": "TN",
	"TURKEY": "TR",
	"TURKMENISTAN": "TM",
	"TURKS AND CAICOS ISLANDS": "TC",
	"TUVALU": "TV",
	"TÜRKIYE": "TR",
	"U.K.": "GB",
	"U.S.": "US",
	"U.S.A.": "US",
	"UAE": "AE",
	"UGANDA": "UG",
	"UK": "GB",
	"UKRAINE": "UA",
	"UNITED ARAB EMIRATES": "AE",
	"UNITED KINGDOM": "GB",
	"UNITED STATES": "US",
	"UNITED STATES MINOR OUTLYING ISLANDS": "UM",
	"UNITED STATES OF AMERICA": "US",
	"URUGUAY": "UY",
	"US OF A": "US",
	"USA": "US",
	"UZBEKISTAN": "UZ",
	"VANUATU": "VU",
	"VENEZUELA": "VE",
	"VIET NAM": "VN",
	"VIETNAM": "VN",
	"VIRGIN ISLANDS (BRITISH)": "VG",
	"VIRGIN ISLANDS (U.S.)": "VI",
	"WALES": "GB",
	"WALLIS AND FUTUNA": "WF",
	"WESTERN SAHARA": "EH",
	"YEMEN": "YE",
	"ZAMBIA": "ZM",
	"ZIMBABWE": "ZW",
	"ÅLAND ISLANDS": "AX",
};

/** Return ISO-3166-1 alpha-2 or null if unrecognized / empty. */
export function normalizeCountryCode(value: string): string | null {
	if (!value?.trim()) return null;
	const raw = value.trim();
	const upper = raw.toUpperCase();
	if (upper.length === 2 && ISO_CODES.has(upper)) return upper;
	const mapped = COUNTRY_ALIASES[aliasKey(raw)];
	if (mapped && ISO_CODES.has(mapped)) return mapped;
	return null;
}
